### ISSUE TITLE
Does not sound

### ISSUE THREAD

**Issue by 9acca9** [nathan-fiscaletti/keyboardsounds#5]
HI
I try your work.
I dont have any error, but... dont sound.
```
kbs status
Status: Running, Volume: 100%, PID: 7913, Profile: ios
```
What i can try to fix it?
(im using a ARCH based distro)

Thanks.

**Comment by nathan-fiscaletti** [comment]
I've not directly tested this on an ARCH based distro yet, but can you attempt running the `kbs start` command with root privileges?

**Comment by 9acca9** [comment]
Thanks, i get this error when executed like root
```
[🔴] × sudo keyboardsounds start
Traceback (most recent call last):
  File "/home/panchines/.local/bin/keyboardsounds", line 5, in <module>
    from keyboardsounds.main import main
ModuleNotFoundError: No module named 'keyboardsounds'
```

**Comment by nathan-fiscaletti** [comment]
You may need to install the package while using the root user.
```
$ sudo su -
$ pip install keyboardsounds
```

**Comment by nathan-fiscaletti** [comment]
Did this solve your issue?

**Comment by nathan-fiscaletti** [comment]
I'm closing this issue since I haven't heard back in three weeks. If the issue is still persisting, please feel free to open it again.
