### ISSUE TITLE
Encounter `TypeError: can only concatenate str (not "list") to str` when running this on macOS

### ISSUE THREAD

**Issue by huangboming** [nathan-fiscaletti/keyboardsounds#9]
Env:

- Machine: Macbook pro M2
- OS: Sonoma 14.5
- Python: 3.11
- `keyboardsounds`: 5.7.7 (just installed with `pip install keyboardsounds` few minutes ago, didn't configure anything)

What happened?

I was trying to run the `keyboardsounds` with `kbs start`, then I encountered the following error:

```shell
kbs start
Traceback (most recent call last):
  File "/opt/homebrew/bin/kbs", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/keyboardsounds/main.py", line 59, in main
    (
TypeError: can only concatenate str (not "list") to str
```

My idea:

![Screenshot 2024-07-07 at 19 06 37](https://github.com/nathan-fiscaletti/keyboardsounds/assets/48573436/930df421-570b-43a6-b0bb-b946de75b269)

After reading the source code and debugging, I found that the error occurred because `win_messages` is a list if the OS is not Windows. After changing `win_messages = []` in line 47 to `win_messages = ""`, the program works.

**Comment by nathan-fiscaletti** [comment]
Thanks for reporting this! You can feel free to make a pull request with the changes (if you'd like), or I can update it sometime in the next week.
